[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Lalitha Janneti", email = "lalithajanneti@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "fastapi>=0.142.2",
    "groq>=1.7.0",
    "ollama>=0.6.3",
    "python-dotenv>=1.2.4",
    "requests>=2.34.2",
    "uvicorn>=0.54.0",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
